[package]
name = "code_samples_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
mysql = "24.0.0"
eframe = "0.25.0"
futures = "0.3.30"